---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Metricbeat.
  package: name=metricbeat state=latest

- include: config.yml
  when: metricbeat_create_config | bool

- name: Ensure Metricbeat is started and enabled at boot.
  service:
    name: metricbeat
    state: restarted
    enabled: true